version: '2.1'
services:
  frontend:
    build: .
    image: backend
    container_name: ticket-backend
    hostname: ticket-backend
    ports:
      - "8181:8181"
networks:
    default:
      external:
        name: frontendnet